// Code generated by gen_closed_db_calls.go (go generate ./database); DO NOT EDIT.

package database

import (
	"time"

	"github.com/aunefyren/treningheten/models"

	"github.com/google/uuid"
)

var _ = time.Time{}
var _ = uuid.UUID{}
var _ = models.User{}

// closedDBCalls maps each exported function to a call with zero-value arguments.
// The bool says whether the function reports errors (and so must fail on a dead database).
var closedDBCalls = []struct {
	name         string
	returnsError bool
	call         func() error
}{
	{"BumpObservedMaxHeartrate", true, func() error { err := BumpObservedMaxHeartrate(uuid.UUID{}, 0); return err }},
	{"CensorUserObject", false, func() error { CensorUserObject(models.User{}); return nil }},
	{"CheckIfAchievementsExistsInDB", true, func() error { _, err := CheckIfAchievementsExistsInDB(); return err }},
	{"ClearStravaConnectionForUser", true, func() error { err := ClearStravaConnectionForUser(uuid.UUID{}); return err }},
	{"ConsumeAuthorizationCode", true, func() error { err := ConsumeAuthorizationCode(uuid.UUID{}); return err }},
	{"CountStravaActivitiesInExercise", true, func() error { _, err := CountStravaActivitiesInExercise(uuid.UUID{}); return err }},
	{"CreateActionInDB", true, func() error { _, err := CreateActionInDB(models.Action{}); return err }},
	{"CreateAuthorizationCode", true, func() error { err := CreateAuthorizationCode(&models.OAuthAuthorizationCode{}); return err }},
	{"CreateExerciseDayForGoalInDatabase", true, func() error { _, err := CreateExerciseDayForGoalInDatabase(models.ExerciseDay{}); return err }},
	{"CreateExerciseDayInDB", true, func() error { err := CreateExerciseDayInDB(models.ExerciseDay{}); return err }},
	{"CreateExerciseForExerciseDayInDatabase", true, func() error { err := CreateExerciseForExerciseDayInDatabase(models.Exercise{}); return err }},
	{"CreateExerciseInDB", true, func() error { _, err := CreateExerciseInDB(models.Exercise{}); return err }},
	{"CreateGearInDB", true, func() error { _, err := CreateGearInDB(models.Gear{}); return err }},
	{"CreateGoalInDB", true, func() error { _, err := CreateGoalInDB(models.Goal{}); return err }},
	{"CreateMediaConnectionInDB", true, func() error { _, err := CreateMediaConnectionInDB(models.MediaConnection{}); return err }},
	{"CreateOAuthClient", true, func() error { err := CreateOAuthClient(&models.OAuthClient{}); return err }},
	{"CreateOperationInDB", true, func() error { _, err := CreateOperationInDB(models.Operation{}); return err }},
	{"CreateOperationSetInDB", true, func() error { _, err := CreateOperationSetInDB(models.OperationSet{}); return err }},
	{"CreatePersonalAccessToken", true, func() error { err := CreatePersonalAccessToken(&models.PersonalAccessToken{}); return err }},
	{"CreatePrizeInDB", true, func() error { err := CreatePrizeInDB(models.Prize{}); return err }},
	{"CreateRefreshToken", true, func() error { err := CreateRefreshToken(&models.OAuthRefreshToken{}); return err }},
	{"CreateSeasonInDB", true, func() error { err := CreateSeasonInDB(models.Season{}); return err }},
	{"CreateSickleave", true, func() error { err := CreateSickleave(models.Sickleave{}); return err }},
	{"CreateSubscriptionInDB", true, func() error { _, err := CreateSubscriptionInDB(models.Subscription{}); return err }},
	{"CreateWeightInDB", true, func() error { _, err := CreateWeightInDB(models.WeightValue{}); return err }},
	{"CreateWheelview", true, func() error { err := CreateWheelview(models.Wheelview{}); return err }},
	{"DeleteIntegrationStatus", true, func() error { err := DeleteIntegrationStatus(uuid.UUID{}, ""); return err }},
	{"DeleteInviteByID", true, func() error { err := DeleteInviteByID(uuid.UUID{}); return err }},
	{"DeleteMediaConnectionForUserProvider", true, func() error { err := DeleteMediaConnectionForUserProvider(uuid.UUID{}, ""); return err }},
	{"DeleteNewsPost", true, func() error { err := DeleteNewsPost(uuid.UUID{}); return err }},
	{"DisableGoalInDBUsingGoalID", true, func() error { err := DisableGoalInDBUsingGoalID(uuid.UUID{}); return err }},
	{"DisableGoalsForUserInUnfinishedSeasons", true, func() error { _, err := DisableGoalsForUserInUnfinishedSeasons(uuid.UUID{}, time.Time{}); return err }},
	{"GenerateRandomInvite", true, func() error { _, err := GenerateRandomInvite(); return err }},
	{"GenerateRandomResetCodeForUser", true, func() error { _, err := GenerateRandomResetCodeForUser(uuid.UUID{}, false); return err }},
	{"GenerateRandomVerificationCodeForUser", true, func() error { _, err := GenerateRandomVerificationCodeForUser(uuid.UUID{}); return err }},
	{"GetAchievementByID", true, func() error { _, err := GetAchievementByID(uuid.UUID{}); return err }},
	{"GetAchievementDelegationByAchievementIDAndUserID", true, func() error {
		_, err := GetAchievementDelegationByAchievementIDAndUserID(uuid.UUID{}, uuid.UUID{})
		return err
	}},
	{"GetAchievementDelegationByIDAndUserID", true, func() error { _, _, err := GetAchievementDelegationByIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetActionByHevyTemplateID", true, func() error { _, err := GetActionByHevyTemplateID(""); return err }},
	{"GetActionByID", true, func() error { _, err := GetActionByID(uuid.UUID{}); return err }},
	{"GetActionByName", true, func() error { _, err := GetActionByName(""); return err }},
	{"GetActionByStravaName", true, func() error { _, err := GetActionByStravaName(""); return err }},
	{"GetActionsDoneUsingUserID", true, func() error { _, err := GetActionsDoneUsingUserID(uuid.UUID{}); return err }},
	{"GetActiveGoalsForUserIDAndDate", true, func() error { _, err := GetActiveGoalsForUserIDAndDate(uuid.UUID{}, ""); return err }},
	{"GetActivityGoalSettingForUserAndAction", true, func() error { _, err := GetActivityGoalSettingForUserAndAction(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetActivityGoalSettingsForUserID", true, func() error { _, err := GetActivityGoalSettingsForUserID(uuid.UUID{}); return err }},
	{"GetActivityTypeActions", true, func() error { _, err := GetActivityTypeActions(); return err }},
	{"GetAdminStatsCounts", true, func() error { _, err := GetAdminStatsCounts(time.Time{}); return err }},
	{"GetAllAchievements", true, func() error { _, err := GetAllAchievements(); return err }},
	{"GetAllEnabledAchievements", true, func() error { _, err := GetAllEnabledAchievements(); return err }},
	{"GetAllEnabledActions", true, func() error { _, err := GetAllEnabledActions(); return err }},
	{"GetAllEnabledExerciseDays", true, func() error { _, err := GetAllEnabledExerciseDays(); return err }},
	{"GetAllEnabledInvites", true, func() error { _, err := GetAllEnabledInvites(); return err }},
	{"GetAllEnabledSeasons", true, func() error { _, err := GetAllEnabledSeasons(); return err }},
	{"GetAllExerciseByIDAndUserID", true, func() error { _, err := GetAllExerciseByIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetAllExerciseDays", true, func() error { _, err := GetAllExerciseDays(); return err }},
	{"GetAllExerciseDaysWithExerciseByUserID", true, func() error { _, err := GetAllExerciseDaysWithExerciseByUserID(uuid.UUID{}); return err }},
	{"GetAllExercisesForMediaSync", true, func() error { _, err := GetAllExercisesForMediaSync(uuid.UUID{}); return err }},
	{"GetAllSubscriptionForUserByUserIDAndEndpoint", true, func() error { _, _, err := GetAllSubscriptionForUserByUserIDAndEndpoint(uuid.UUID{}, ""); return err }},
	{"GetAllSubscriptionsForAccountAlertsForUserID", true, func() error { _, err := GetAllSubscriptionsForAccountAlertsForUserID(uuid.UUID{}); return err }},
	{"GetAllSubscriptionsForAchievementsForUserID", true, func() error { _, _, err := GetAllSubscriptionsForAchievementsForUserID(uuid.UUID{}); return err }},
	{"GetAllSubscriptionsForNews", true, func() error { _, _, err := GetAllSubscriptionsForNews(); return err }},
	{"GetAllSubscriptionsForSundayAlerts", true, func() error { _, _, err := GetAllSubscriptionsForSundayAlerts(); return err }},
	{"GetAllSubscriptionsForUserByUserID", true, func() error { _, err := GetAllSubscriptionsForUserByUserID(uuid.UUID{}); return err }},
	{"GetAllUserInformation", true, func() error { _, err := GetAllUserInformation(uuid.UUID{}); return err }},
	{"GetAllUserInformationByEmail", true, func() error { _, err := GetAllUserInformationByEmail(""); return err }},
	{"GetAllUserInformationByResetCode", true, func() error { _, err := GetAllUserInformationByResetCode(""); return err }},
	{"GetAllUsersIncludingDisabled", true, func() error { _, err := GetAllUsersIncludingDisabled(); return err }},
	{"GetAllUsersUncensored", true, func() error { _, err := GetAllUsersUncensored(); return err }},
	{"GetAllUsersWithSundayAlertsEnabled", true, func() error { _, err := GetAllUsersWithSundayAlertsEnabled(); return err }},
	{"GetAllUsersWithSundayAlertsEnabledUncensored", true, func() error { _, err := GetAllUsersWithSundayAlertsEnabledUncensored(); return err }},
	{"GetAmountOfEnabledUsers", true, func() error { _, err := GetAmountOfEnabledUsers(); return err }},
	{"GetAuthorizationCodeByHash", true, func() error { _, err := GetAuthorizationCodeByHash(""); return err }},
	{"GetDebtByDebtID", true, func() error { _, _, err := GetDebtByDebtID(uuid.UUID{}); return err }},
	{"GetDebtForWeekForUser", true, func() error { _, _, err := GetDebtForWeekForUser(time.Time{}, uuid.UUID{}); return err }},
	{"GetDebtForWeekForUserInSeasonID", true, func() error {
		_, _, err := GetDebtForWeekForUserInSeasonID(time.Time{}, uuid.UUID{}, uuid.UUID{})
		return err
	}},
	{"GetDebtInSeasonLostByUserID", true, func() error { _, _, err := GetDebtInSeasonLostByUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetDebtInSeasonWonByUserID", true, func() error { _, _, err := GetDebtInSeasonWonByUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetDebtsForUserIDsBetweenDates", true, func() error { _, err := GetDebtsForUserIDsBetweenDates(nil, time.Time{}, time.Time{}); return err }},
	{"GetDelegatedAchievementsByUserID", true, func() error { _, _, err := GetDelegatedAchievementsByUserID(uuid.UUID{}); return err }},
	{"GetDistinctDelegatedAchievementsByUserID", true, func() error { _, _, err := GetDistinctDelegatedAchievementsByUserID(uuid.UUID{}); return err }},
	{"GetEnabledWeightsByWeightIDAndUserID", true, func() error { _, err := GetEnabledWeightsByWeightIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetEnabledWeightsForUser", true, func() error { _, err := GetEnabledWeightsForUser(uuid.UUID{}); return err }},
	{"GetExerciseByExerciseDayID", true, func() error { _, err := GetExerciseByExerciseDayID(uuid.UUID{}); return err }},
	{"GetExerciseByIDAndUserID", true, func() error { _, err := GetExerciseByIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetExerciseDayByDateAndGoal", true, func() error { _, err := GetExerciseDayByDateAndGoal(uuid.UUID{}, time.Time{}); return err }},
	{"GetExerciseDayByDateAndUserID", true, func() error { _, err := GetExerciseDayByDateAndUserID(uuid.UUID{}, time.Time{}); return err }},
	{"GetExerciseDayByGoalAndDate", true, func() error { _, err := GetExerciseDayByGoalAndDate(uuid.UUID{}, time.Time{}); return err }},
	{"GetExerciseDayByID", true, func() error { _, err := GetExerciseDayByID(uuid.UUID{}); return err }},
	{"GetExerciseDayByIDAndUserID", true, func() error { _, err := GetExerciseDayByIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetExerciseDayByUserIDAndDate", true, func() error { _, err := GetExerciseDayByUserIDAndDate(uuid.UUID{}, time.Time{}); return err }},
	{"GetExerciseDaysBetweenDatesUsingDatesAndUserID", true, func() error {
		_, err := GetExerciseDaysBetweenDatesUsingDatesAndUserID(uuid.UUID{}, time.Time{}, time.Time{})
		return err
	}},
	{"GetExerciseDaysForSharingUsersInListUsingDates", true, func() error {
		_, err := GetExerciseDaysForSharingUsersInListUsingDates(nil, time.Time{}, time.Time{})
		return err
	}},
	{"GetExerciseDaysForSharingUsersUsingDates", true, func() error { _, err := GetExerciseDaysForSharingUsersUsingDates(time.Time{}, time.Time{}); return err }},
	{"GetExerciseDaysForUserUsingUserID", true, func() error { _, err := GetExerciseDaysForUserUsingUserID(uuid.UUID{}); return err }},
	{"GetExerciseDaysForUserUsingUserIDAndGoalID", true, func() error {
		_, err := GetExerciseDaysForUserUsingUserIDAndGoalID(uuid.UUID{}, uuid.UUID{})
		return err
	}},
	{"GetExerciseForUserWithHevyWorkoutID", true, func() error { _, err := GetExerciseForUserWithHevyWorkoutID(uuid.UUID{}, ""); return err }},
	{"GetExerciseForUserWithStravaID", true, func() error { _, err := GetExerciseForUserWithStravaID(uuid.UUID{}, ""); return err }},
	{"GetExercisesForMediaBackfill", true, func() error { _, err := GetExercisesForMediaBackfill(uuid.UUID{}, time.Time{}); return err }},
	{"GetExercisesForMediaReconcile", true, func() error { _, err := GetExercisesForMediaReconcile(uuid.UUID{}, time.Time{}); return err }},
	{"GetGearByID", true, func() error { _, err := GetGearByID(uuid.UUID{}); return err }},
	{"GetGearByIDAndUserID", true, func() error { _, err := GetGearByIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetGearByStravaGearIDAndUserID", true, func() error { _, err := GetGearByStravaGearIDAndUserID("", uuid.UUID{}); return err }},
	{"GetGearDistanceTotalsForUser", true, func() error { _, err := GetGearDistanceTotalsForUser(uuid.UUID{}); return err }},
	{"GetGearForUser", true, func() error { _, err := GetGearForUser(uuid.UUID{}); return err }},
	{"GetGoalFromUserWithinSeason", true, func() error { _, err := GetGoalFromUserWithinSeason(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetGoalUsingGoalID", true, func() error { _, err := GetGoalUsingGoalID(uuid.UUID{}); return err }},
	{"GetGoalsForUserUsingUserID", true, func() error { _, err := GetGoalsForUserUsingUserID(uuid.UUID{}); return err }},
	{"GetGoalsFromWithinSeason", true, func() error { _, err := GetGoalsFromWithinSeason(uuid.UUID{}); return err }},
	{"GetHevyExerciseForUserNearTime", true, func() error { _, err := GetHevyExerciseForUserNearTime(uuid.UUID{}, time.Time{}, 0); return err }},
	{"GetHevyUsers", true, func() error { _, err := GetHevyUsers(); return err }},
	{"GetIntegrationStatus", true, func() error { _, err := GetIntegrationStatus(uuid.UUID{}, ""); return err }},
	{"GetInviteByID", true, func() error { _, err := GetInviteByID(uuid.UUID{}); return err }},
	{"GetMediaConnectionForUserProvider", true, func() error { _, err := GetMediaConnectionForUserProvider(uuid.UUID{}, ""); return err }},
	{"GetMediaConnectionsForProvider", true, func() error { _, err := GetMediaConnectionsForProvider(""); return err }},
	{"GetMediaConnectionsForUser", true, func() error { _, err := GetMediaConnectionsForUser(uuid.UUID{}); return err }},
	{"GetMediaPlaybackForExercise", true, func() error { _, err := GetMediaPlaybackForExercise(uuid.UUID{}); return err }},
	{"GetNewsPostByNewsID", true, func() error { _, err := GetNewsPostByNewsID(uuid.UUID{}); return err }},
	{"GetNewsPosts", true, func() error { _, err := GetNewsPosts(); return err }},
	{"GetOAuthClientByClientID", true, func() error { _, err := GetOAuthClientByClientID(""); return err }},
	{"GetOperationByIDAndUserID", true, func() error { _, err := GetOperationByIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetOperationByStravaIDAndUserIDAndExerciseID", true, func() error {
		_, err := GetOperationByStravaIDAndUserIDAndExerciseID(uuid.UUID{}, 0, uuid.UUID{})
		return err
	}},
	{"GetOperationSetByIDAndUserID", true, func() error { _, err := GetOperationSetByIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetOperationSetByStravaIDAndUserID", true, func() error { _, err := GetOperationSetByStravaIDAndUserID(uuid.UUID{}, 0); return err }},
	{"GetOperationSetByStravaIDAndUserIDAndOperationID", true, func() error {
		_, err := GetOperationSetByStravaIDAndUserIDAndOperationID(uuid.UUID{}, 0, uuid.UUID{})
		return err
	}},
	{"GetOperationSetsByOperationID", true, func() error { _, err := GetOperationSetsByOperationID(uuid.UUID{}); return err }},
	{"GetOperationSetsByOperationIDAndUserID", true, func() error { _, err := GetOperationSetsByOperationIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetOperationSetsByUserID", true, func() error { _, err := GetOperationSetsByUserID(uuid.UUID{}); return err }},
	{"GetOperationsByExerciseID", true, func() error { _, err := GetOperationsByExerciseID(uuid.UUID{}); return err }},
	{"GetOperationsByUserID", true, func() error { _, err := GetOperationsByUserID(uuid.UUID{}); return err }},
	{"GetPersonalAccessTokenByHash", true, func() error { _, err := GetPersonalAccessTokenByHash(""); return err }},
	{"GetPersonalAccessTokensByUser", true, func() error { _, err := GetPersonalAccessTokensByUser(uuid.UUID{}); return err }},
	{"GetPrizeByID", true, func() error { _, _, err := GetPrizeByID(uuid.UUID{}); return err }},
	{"GetPrizeByNameAndQuantity", true, func() error { _, _, err := GetPrizeByNameAndQuantity("", 0); return err }},
	{"GetPrizes", true, func() error { _, _, err := GetPrizes(); return err }},
	{"GetRefreshTokenByHash", true, func() error { _, err := GetRefreshTokenByHash(""); return err }},
	{"GetSeasonByID", true, func() error { _, err := GetSeasonByID(uuid.UUID{}); return err }},
	{"GetSeasonPeerUserIDsForUser", true, func() error { _, err := GetSeasonPeerUserIDsForUser(uuid.UUID{}); return err }},
	{"GetSessionFeedForUser", true, func() error { _, _, err := GetSessionFeedForUser(uuid.UUID{}, models.ActivityFeedFilter{}); return err }},
	{"GetSickleavesForGoalIDsBetweenDates", true, func() error { _, err := GetSickleavesForGoalIDsBetweenDates(nil, time.Time{}, time.Time{}); return err }},
	{"GetStravaExerciseForUserNearTime", true, func() error { _, err := GetStravaExerciseForUserNearTime(uuid.UUID{}, time.Time{}, 0); return err }},
	{"GetStravaExercisesByUserID", true, func() error { _, err := GetStravaExercisesByUserID(uuid.UUID{}); return err }},
	{"GetStravaOperationSetsByUserID", true, func() error { _, err := GetStravaOperationSetsByUserID(uuid.UUID{}); return err }},
	{"GetStravaUsers", true, func() error { _, err := GetStravaUsers(); return err }},
	{"GetStravaUsersWithinSeason", true, func() error { _, err := GetStravaUsersWithinSeason(uuid.UUID{}); return err }},
	{"GetUnchosenDebtForUserByUserID", true, func() error { _, _, err := GetUnchosenDebtForUserByUserID(uuid.UUID{}); return err }},
	{"GetUnpaidDebtForUser", true, func() error { _, _, err := GetUnpaidDebtForUser(uuid.UUID{}); return err }},
	{"GetUnreceivedDebtByUserID", true, func() error { _, _, err := GetUnreceivedDebtByUserID(uuid.UUID{}); return err }},
	{"GetUnusedSickleaveForGoalWithinWeek", true, func() error { _, _, err := GetUnusedSickleaveForGoalWithinWeek(uuid.UUID{}); return err }},
	{"GetUnusedSickleavesForGoalIDs", true, func() error { _, err := GetUnusedSickleavesForGoalIDs(nil); return err }},
	{"GetUnviewedWheelviewByDebtIDAndUserID", true, func() error { _, _, err := GetUnviewedWheelviewByDebtIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"GetUnviewedWheelviewByUserID", true, func() error { _, _, err := GetUnviewedWheelviewByUserID(uuid.UUID{}); return err }},
	{"GetUsedSickleaveForGoalWithinWeek", true, func() error { _, err := GetUsedSickleaveForGoalWithinWeek(time.Time{}, uuid.UUID{}); return err }},
	{"GetUserByIDIncludingDisabled", true, func() error { _, err := GetUserByIDIncludingDisabled(uuid.UUID{}); return err }},
	{"GetUserEmailByUserID", true, func() error { _, _, err := GetUserEmailByUserID(uuid.UUID{}); return err }},
	{"GetUserIDsWithMediaConnections", true, func() error { _, err := GetUserIDsWithMediaConnections(); return err }},
	{"GetUserInformation", true, func() error { _, err := GetUserInformation(uuid.UUID{}); return err }},
	{"GetUserInformationByEmail", true, func() error { _, err := GetUserInformationByEmail(""); return err }},
	{"GetUserInformationIncludingDisabled", true, func() error { _, err := GetUserInformationIncludingDisabled(uuid.UUID{}); return err }},
	{"GetUsersByIDs", true, func() error { _, err := GetUsersByIDs(nil); return err }},
	{"GetUsersInformation", true, func() error { _, err := GetUsersInformation(); return err }},
	{"GetValidExercisesBetweenDatesUsingDatesByUserID", true, func() error {
		_, err := GetValidExercisesBetweenDatesUsingDatesByUserID(uuid.UUID{}, time.Time{}, time.Time{})
		return err
	}},
	{"GetValidExercisesForUserIDsBetweenDates", true, func() error {
		_, err := GetValidExercisesForUserIDsBetweenDates(nil, time.Time{}, time.Time{})
		return err
	}},
	{"GetWheelviewByDebtIDAndUserID", true, func() error { _, _, err := GetWheelviewByDebtIDAndUserID(uuid.UUID{}, uuid.UUID{}); return err }},
	{"RegisterAchievementDelegationInDB", true, func() error { _, err := RegisterAchievementDelegationInDB(models.AchievementDelegation{}); return err }},
	{"RegisterAchievementInDB", true, func() error { _, err := RegisterAchievementInDB(models.Achievement{}); return err }},
	{"RegisterDebtInDB", true, func() error { _, err := RegisterDebtInDB(models.Debt{}); return err }},
	{"RegisterUserInDB", true, func() error { _, err := RegisterUserInDB(models.User{}); return err }},
	{"ReplaceMediaPlaybackForExerciseProvider", true, func() error { err := ReplaceMediaPlaybackForExerciseProvider(uuid.UUID{}, "", nil); return err }},
	{"RevokeAllRefreshTokensForUser", true, func() error { err := RevokeAllRefreshTokensForUser(uuid.UUID{}); return err }},
	{"RevokePersonalAccessToken", true, func() error { err := RevokePersonalAccessToken(uuid.UUID{}, uuid.UUID{}); return err }},
	{"RevokeRefreshToken", true, func() error { err := RevokeRefreshToken(""); return err }},
	{"RevokeRefreshTokenChain", true, func() error { err := RevokeRefreshTokenChain(uuid.UUID{}); return err }},
	{"RotateRefreshToken", true, func() error { err := RotateRefreshToken(uuid.UUID{}, &models.OAuthRefreshToken{}); return err }},
	{"SaveAchievementInDB", true, func() error { _, err := SaveAchievementInDB(models.Achievement{}); return err }},
	{"SaveIntegrationStatus", true, func() error { _, err := SaveIntegrationStatus(models.IntegrationStatus{}); return err }},
	{"SeedActions", false, func() error { SeedActions(); return nil }},
	{"SeedHevyActions", false, func() error { SeedHevyActions(); return nil }},
	{"SeedOAuthClients", false, func() error { SeedOAuthClients(); return nil }},
	{"SetAchievementsToSeenForUser", true, func() error { _, err := SetAchievementsToSeenForUser(uuid.UUID{}); return err }},
	{"SetExerciseCountsTowardGoal", true, func() error { err := SetExerciseCountsTowardGoal(uuid.UUID{}, false); return err }},
	{"SetExerciseIsOn", true, func() error { err := SetExerciseIsOn(uuid.UUID{}, false); return err }},
	{"SetExerciseMediaRetrievedAt", true, func() error { err := SetExerciseMediaRetrievedAt(uuid.UUID{}, time.Time{}); return err }},
	{"SetExerciseMediaSettled", true, func() error { err := SetExerciseMediaSettled(uuid.UUID{}, false); return err }},
	{"SetHevyLastSyncForUser", true, func() error { err := SetHevyLastSyncForUser(uuid.UUID{}, time.Time{}); return err }},
	{"SetSickleaveToUsedByID", true, func() error { err := SetSickleaveToUsedByID(uuid.UUID{}); return err }},
	{"SetStravaCredentialsForUser", true, func() error { err := SetStravaCredentialsForUser(uuid.UUID{}, "", nil); return err }},
	{"SetUsedUserInviteCode", true, func() error { err := SetUsedUserInviteCode("", uuid.UUID{}); return err }},
	{"SetUserEnabled", true, func() error { err := SetUserEnabled(uuid.UUID{}, false); return err }},
	{"SetUserVerification", true, func() error { err := SetUserVerification(uuid.UUID{}, false); return err }},
	{"SetWheelviewToViewedByID", true, func() error { err := SetWheelviewToViewedByID(uuid.UUID{}); return err }},
	{"ToAdminUser", false, func() error { ToAdminUser(models.User{}); return nil }},
	{"TouchPersonalAccessToken", true, func() error { err := TouchPersonalAccessToken(uuid.UUID{}); return err }},
	{"TouchRefreshToken", true, func() error { err := TouchRefreshToken(uuid.UUID{}); return err }},
	{"UnsetPrimaryGearForUser", true, func() error { err := UnsetPrimaryGearForUser(uuid.UUID{}, uuid.UUID{}); return err }},
	{"UpdateActionInDB", true, func() error { _, err := UpdateActionInDB(models.Action{}); return err }},
	{"UpdateBirthDateValueByUserID", true, func() error { err := UpdateBirthDateValueByUserID(uuid.UUID{}, &time.Time{}); return err }},
	{"UpdateDebtPaidStatus", true, func() error { err := UpdateDebtPaidStatus(uuid.UUID{}, uuid.UUID{}); return err }},
	{"UpdateDebtWinner", true, func() error { err := UpdateDebtWinner(uuid.UUID{}, uuid.UUID{}); return err }},
	{"UpdateEmailValueByUserID", true, func() error { err := UpdateEmailValueByUserID(uuid.UUID{}, ""); return err }},
	{"UpdateExerciseByTurningOffByExerciseID", true, func() error { err := UpdateExerciseByTurningOffByExerciseID(uuid.UUID{}); return err }},
	{"UpdateExerciseByTurningOnByExerciseID", true, func() error { err := UpdateExerciseByTurningOnByExerciseID(uuid.UUID{}); return err }},
	{"UpdateExerciseDayInDB", true, func() error { _, err := UpdateExerciseDayInDB(models.ExerciseDay{}); return err }},
	{"UpdateExerciseDayInDatabase", true, func() error { _, err := UpdateExerciseDayInDatabase(models.ExerciseDay{}); return err }},
	{"UpdateExerciseDayNoteInDatabase", true, func() error { err := UpdateExerciseDayNoteInDatabase(uuid.UUID{}, "", "", ""); return err }},
	{"UpdateExerciseInDB", true, func() error { _, err := UpdateExerciseInDB(models.Exercise{}); return err }},
	{"UpdateGearInDB", true, func() error { _, err := UpdateGearInDB(models.Gear{}); return err }},
	{"UpdateMediaConnectionInDB", true, func() error { _, err := UpdateMediaConnectionInDB(models.MediaConnection{}); return err }},
	{"UpdateOperationInDB", true, func() error { _, err := UpdateOperationInDB(models.Operation{}); return err }},
	{"UpdateOperationSetInDB", true, func() error { _, err := UpdateOperationSetInDB(models.OperationSet{}); return err }},
	{"UpdatePasswordValueByUserID", true, func() error { err := UpdatePasswordValueByUserID(uuid.UUID{}, ""); return err }},
	{"UpdateSubscription", true, func() error { _, err := UpdateSubscription(models.Subscription{}); return err }},
	{"UpdateSubscriptionAccountAlertByEndpointAndUserID", true, func() error {
		err := UpdateSubscriptionAccountAlertByEndpointAndUserID(uuid.UUID{}, "", false)
		return err
	}},
	{"UpdateSubscriptionAchievementByEndpointAndUserID", true, func() error {
		err := UpdateSubscriptionAchievementByEndpointAndUserID(uuid.UUID{}, "", false)
		return err
	}},
	{"UpdateSubscriptionForUserByUserIDAndEndpoint", true, func() error {
		err := UpdateSubscriptionForUserByUserIDAndEndpoint(uuid.UUID{}, "", false, false, false, nil)
		return err
	}},
	{"UpdateSubscriptionNewsByEndpointAndUserID", true, func() error { err := UpdateSubscriptionNewsByEndpointAndUserID(uuid.UUID{}, "", false); return err }},
	{"UpdateSubscriptionSundayReminderByEndpointAndUserID", true, func() error {
		err := UpdateSubscriptionSundayReminderByEndpointAndUserID(uuid.UUID{}, "", false)
		return err
	}},
	{"UpdateSundayAlertValueByUserID", true, func() error { err := UpdateSundayAlertValueByUserID(uuid.UUID{}, false); return err }},
	{"UpdateUser", true, func() error { _, err := UpdateUser(models.User{}); return err }},
	{"UpdateUserValuesByUserID", true, func() error { err := UpdateUserValuesByUserID(uuid.UUID{}, "", "", false, &time.Time{}); return err }},
	{"UpdateWeightInDB", true, func() error { _, err := UpdateWeightInDB(models.WeightValue{}); return err }},
	{"UpsertActivityGoalSettingInDB", true, func() error { err := UpsertActivityGoalSettingInDB(uuid.UUID{}, uuid.UUID{}, false); return err }},
	{"VerifyIfAchievedByUser", true, func() error { _, err := VerifyIfAchievedByUser(uuid.UUID{}, uuid.UUID{}); return err }},
	{"VerifyUniqueSeasonName", true, func() error { _, err := VerifyUniqueSeasonName(""); return err }},
	{"VerifyUniqueUserEmail", true, func() error { _, err := VerifyUniqueUserEmail(""); return err }},
	{"VerifyUnusedUserInviteCode", true, func() error { _, err := VerifyUnusedUserInviteCode(""); return err }},
	{"VerifyUserGoalInSeason", true, func() error { _, _, err := VerifyUserGoalInSeason(uuid.UUID{}, uuid.UUID{}); return err }},
	{"VerifyUserHasVerificationCode", true, func() error { _, err := VerifyUserHasVerificationCode(uuid.UUID{}); return err }},
	{"VerifyUserIsEnabled", true, func() error { _, err := VerifyUserIsEnabled(uuid.UUID{}); return err }},
	{"VerifyUserIsVerified", true, func() error { _, err := VerifyUserIsVerified(uuid.UUID{}); return err }},
	{"VerifyUserVerificationCodeMatches", true, func() error { _, _, err := VerifyUserVerificationCodeMatches(uuid.UUID{}, ""); return err }},
}
