//go:build ignore

// gen_closed_db_calls emits database/closed_db_calls_test.go: one call per exported database
// function, with zero-value arguments, for the dead-database sweep.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func zero(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return `""`
		case "bool":
			return "false"
		case "int", "int64", "int32", "uint", "float64", "float32":
			return "0"
		}
		return t.Name + "{}"
	case *ast.SelectorExpr:
		name := fmt.Sprintf("%s.%s", t.X.(*ast.Ident).Name, t.Sel.Name)
		if name == "time.Duration" {
			return "0"
		}
		return name + "{}"
	case *ast.StarExpr:
		return "&" + zero(t.X)
	case *ast.ArrayType:
		return "nil"
	case *ast.MapType:
		return "nil"
	}
	return "nil"
}

func main() {
	dir := os.Args[1]
	fset := token.NewFileSet()
	matches, _ := filepath.Glob(filepath.Join(dir, "*.go"))
	type fn struct {
		name, call   string
		returnsError bool
	}
	var fns []fn
	for _, path := range matches {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			panic(err)
		}
		for _, decl := range file.Decls {
			f, ok := decl.(*ast.FuncDecl)
			if !ok || f.Recv != nil || !f.Name.IsExported() {
				continue
			}
			switch f.Name.Name {
			case "Connect", "CreateTable", "Migrate", "InitializeSQLiteDB":
				continue
			}
			args := []string{}
			for _, param := range f.Type.Params.List {
				n := len(param.Names)
				if n == 0 {
					n = 1
				}
				for i := 0; i < n; i++ {
					args = append(args, zero(param.Type))
				}
			}
			returnsError := false
			results := 0
			if f.Type.Results != nil {
				for _, r := range f.Type.Results.List {
					n := len(r.Names)
					if n == 0 {
						n = 1
					}
					results += n
				}
				last := f.Type.Results.List[len(f.Type.Results.List)-1]
				if id, ok := last.Type.(*ast.Ident); ok && id.Name == "error" {
					returnsError = true
				}
			}
			call := fmt.Sprintf("%s(%s)", f.Name.Name, strings.Join(args, ", "))
			if returnsError {
				blanks := strings.Repeat("_, ", results-1)
				call = fmt.Sprintf("%serr := %s; return err", blanks, call)
			} else {
				call = call + "; return nil"
			}
			fns = append(fns, fn{f.Name.Name, call, returnsError})
		}
	}
	sort.Slice(fns, func(i, j int) bool { return fns[i].name < fns[j].name })

	var out bytes.Buffer
	out.WriteString("// Code generated by gen_closed_db_calls.go (go generate ./database); DO NOT EDIT.\n\npackage database\n\nimport (\n\t\"time\"\n\n\t\"github.com/aunefyren/treningheten/models\"\n\n\t\"github.com/google/uuid\"\n)\n\n")
	out.WriteString("var _ = time.Time{}\nvar _ = uuid.UUID{}\nvar _ = models.User{}\n\n")
	out.WriteString("// closedDBCalls maps each exported function to a call with zero-value arguments.\n// The bool says whether the function reports errors (and so must fail on a dead database).\nvar closedDBCalls = []struct {\n\tname string\n\treturnsError bool\n\tcall func() error\n}{\n")
	for _, f := range fns {
		fmt.Fprintf(&out, "\t{%q, %v, func() error { %s }},\n", f.name, f.returnsError, f.call)
	}
	out.WriteString("}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		os.Stdout.Write(out.Bytes())
		panic(err)
	}
	os.Stdout.Write(formatted)
}
